// код для генерации
// protoc -I proto `
//   --go_out=pkg/proto --go_opt=paths=source_relative `
//   --go-grpc_out=pkg/proto --go-grpc_opt=paths=source_relative `
//   proto/pact/telegram/v1/telegram.proto

// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.2
// source: pact/telegram/v1/telegram.proto

package telegramv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// CreateSessionRequest - пустой запрос для создания сессии
type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{0}
}

// CreateSessionResponse содержит данные для авторизации
type CreateSessionResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id уникальный идентификатор созданной сессии
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// qr_code данные для генерации QR кода (токен авторизации)
	QrCode        string `protobuf:"bytes,2,opt,name=qr_code,json=qrCode,proto3" json:"qr_code,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{1}
}

func (x *CreateSessionResponse) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *CreateSessionResponse) GetQrCode() string {
	if x != nil {
		return x.QrCode
	}
	return ""
}

// DeleteSessionRequest запрос на удаление сессии
type DeleteSessionRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id идентификатор удаляемой сессии
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionRequest) Reset() {
	*x = DeleteSessionRequest{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionRequest) ProtoMessage() {}

func (x *DeleteSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionRequest.ProtoReflect.Descriptor instead.
func (*DeleteSessionRequest) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{2}
}

func (x *DeleteSessionRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// DeleteSessionResponse пустой ответ на удаление
type DeleteSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DeleteSessionResponse) Reset() {
	*x = DeleteSessionResponse{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DeleteSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DeleteSessionResponse) ProtoMessage() {}

func (x *DeleteSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DeleteSessionResponse.ProtoReflect.Descriptor instead.
func (*DeleteSessionResponse) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{3}
}

// SendMessageRequest запрос на отправку сообщения
type SendMessageRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// session_id идентификатор сессии, через которую отправляем
	SessionId string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	// peer получатель сообщения (username, телефон или ID)
	Peer string `protobuf:"bytes,2,opt,name=peer,proto3" json:"peer,omitempty"` // e.g. @durov
	// text текст отправляемого сообщения
	Text          string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageRequest) Reset() {
	*x = SendMessageRequest{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageRequest) ProtoMessage() {}

func (x *SendMessageRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageRequest.ProtoReflect.Descriptor instead.
func (*SendMessageRequest) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{4}
}

func (x *SendMessageRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

func (x *SendMessageRequest) GetPeer() string {
	if x != nil {
		return x.Peer
	}
	return ""
}

func (x *SendMessageRequest) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

// SendMessageResponse содержит ID отправленного сообщения
type SendMessageResponse struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id идентификатор сообщения в Telegram
	MessageId     int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SendMessageResponse) Reset() {
	*x = SendMessageResponse{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SendMessageResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SendMessageResponse) ProtoMessage() {}

func (x *SendMessageResponse) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SendMessageResponse.ProtoReflect.Descriptor instead.
func (*SendMessageResponse) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{5}
}

func (x *SendMessageResponse) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

// SubscribeMessagesRequest запрос на подписку на сообщения
type SubscribeMessagesRequest struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id идентификатор сообщения в Telegram
	SessionId     string `protobuf:"bytes,1,opt,name=session_id,json=sessionId,proto3" json:"session_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SubscribeMessagesRequest) Reset() {
	*x = SubscribeMessagesRequest{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SubscribeMessagesRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SubscribeMessagesRequest) ProtoMessage() {}

func (x *SubscribeMessagesRequest) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SubscribeMessagesRequest.ProtoReflect.Descriptor instead.
func (*SubscribeMessagesRequest) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{6}
}

func (x *SubscribeMessagesRequest) GetSessionId() string {
	if x != nil {
		return x.SessionId
	}
	return ""
}

// MessageUpdate содержит информацию о входящем сообщении
type MessageUpdate struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// message_id идентификатор сообщения в Telegram
	MessageId int64 `protobuf:"varint,1,opt,name=message_id,json=messageId,proto3" json:"message_id,omitempty"`
	// from отправитель сообщения (username или имя)
	From string `protobuf:"bytes,2,opt,name=from,proto3" json:"from,omitempty"`
	// text текст сообщения
	Text string `protobuf:"bytes,3,opt,name=text,proto3" json:"text,omitempty"`
	// timestamp время отправки
	Timestamp     int64 `protobuf:"varint,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MessageUpdate) Reset() {
	*x = MessageUpdate{}
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MessageUpdate) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MessageUpdate) ProtoMessage() {}

func (x *MessageUpdate) ProtoReflect() protoreflect.Message {
	mi := &file_pact_telegram_v1_telegram_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MessageUpdate.ProtoReflect.Descriptor instead.
func (*MessageUpdate) Descriptor() ([]byte, []int) {
	return file_pact_telegram_v1_telegram_proto_rawDescGZIP(), []int{7}
}

func (x *MessageUpdate) GetMessageId() int64 {
	if x != nil {
		return x.MessageId
	}
	return 0
}

func (x *MessageUpdate) GetFrom() string {
	if x != nil {
		return x.From
	}
	return ""
}

func (x *MessageUpdate) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *MessageUpdate) GetTimestamp() int64 {
	if x != nil {
		return x.Timestamp
	}
	return 0
}

var File_pact_telegram_v1_telegram_proto protoreflect.FileDescriptor

const file_pact_telegram_v1_telegram_proto_rawDesc = "" +
	"\n" +
	"\x1fpact/telegram/v1/telegram.proto\x12\x10pact.telegram.v1\"\x16\n" +
	"\x14CreateSessionRequest\"O\n" +
	"\x15CreateSessionResponse\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x17\n" +
	"\aqr_code\x18\x02 \x01(\tR\x06qrCode\"5\n" +
	"\x14DeleteSessionRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"\x17\n" +
	"\x15DeleteSessionResponse\"[\n" +
	"\x12SendMessageRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\x12\x12\n" +
	"\x04peer\x18\x02 \x01(\tR\x04peer\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\"4\n" +
	"\x13SendMessageResponse\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\"9\n" +
	"\x18SubscribeMessagesRequest\x12\x1d\n" +
	"\n" +
	"session_id\x18\x01 \x01(\tR\tsessionId\"t\n" +
	"\rMessageUpdate\x12\x1d\n" +
	"\n" +
	"message_id\x18\x01 \x01(\x03R\tmessageId\x12\x12\n" +
	"\x04from\x18\x02 \x01(\tR\x04from\x12\x12\n" +
	"\x04text\x18\x03 \x01(\tR\x04text\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\x03R\ttimestamp2\x95\x03\n" +
	"\x0fTelegramService\x12`\n" +
	"\rCreateSession\x12&.pact.telegram.v1.CreateSessionRequest\x1a'.pact.telegram.v1.CreateSessionResponse\x12`\n" +
	"\rDeleteSession\x12&.pact.telegram.v1.DeleteSessionRequest\x1a'.pact.telegram.v1.DeleteSessionResponse\x12Z\n" +
	"\vSendMessage\x12$.pact.telegram.v1.SendMessageRequest\x1a%.pact.telegram.v1.SendMessageResponse\x12b\n" +
	"\x11SubscribeMessages\x12*.pact.telegram.v1.SubscribeMessagesRequest\x1a\x1f.pact.telegram.v1.MessageUpdate0\x01BCZAgithub.com/KolManis/tt_pact/pkg/proto/pact/telegram/v1;telegramv1b\x06proto3"

var (
	file_pact_telegram_v1_telegram_proto_rawDescOnce sync.Once
	file_pact_telegram_v1_telegram_proto_rawDescData []byte
)

func file_pact_telegram_v1_telegram_proto_rawDescGZIP() []byte {
	file_pact_telegram_v1_telegram_proto_rawDescOnce.Do(func() {
		file_pact_telegram_v1_telegram_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_pact_telegram_v1_telegram_proto_rawDesc), len(file_pact_telegram_v1_telegram_proto_rawDesc)))
	})
	return file_pact_telegram_v1_telegram_proto_rawDescData
}

var file_pact_telegram_v1_telegram_proto_msgTypes = make([]protoimpl.MessageInfo, 8)
var file_pact_telegram_v1_telegram_proto_goTypes = []any{
	(*CreateSessionRequest)(nil),     // 0: pact.telegram.v1.CreateSessionRequest
	(*CreateSessionResponse)(nil),    // 1: pact.telegram.v1.CreateSessionResponse
	(*DeleteSessionRequest)(nil),     // 2: pact.telegram.v1.DeleteSessionRequest
	(*DeleteSessionResponse)(nil),    // 3: pact.telegram.v1.DeleteSessionResponse
	(*SendMessageRequest)(nil),       // 4: pact.telegram.v1.SendMessageRequest
	(*SendMessageResponse)(nil),      // 5: pact.telegram.v1.SendMessageResponse
	(*SubscribeMessagesRequest)(nil), // 6: pact.telegram.v1.SubscribeMessagesRequest
	(*MessageUpdate)(nil),            // 7: pact.telegram.v1.MessageUpdate
}
var file_pact_telegram_v1_telegram_proto_depIdxs = []int32{
	0, // 0: pact.telegram.v1.TelegramService.CreateSession:input_type -> pact.telegram.v1.CreateSessionRequest
	2, // 1: pact.telegram.v1.TelegramService.DeleteSession:input_type -> pact.telegram.v1.DeleteSessionRequest
	4, // 2: pact.telegram.v1.TelegramService.SendMessage:input_type -> pact.telegram.v1.SendMessageRequest
	6, // 3: pact.telegram.v1.TelegramService.SubscribeMessages:input_type -> pact.telegram.v1.SubscribeMessagesRequest
	1, // 4: pact.telegram.v1.TelegramService.CreateSession:output_type -> pact.telegram.v1.CreateSessionResponse
	3, // 5: pact.telegram.v1.TelegramService.DeleteSession:output_type -> pact.telegram.v1.DeleteSessionResponse
	5, // 6: pact.telegram.v1.TelegramService.SendMessage:output_type -> pact.telegram.v1.SendMessageResponse
	7, // 7: pact.telegram.v1.TelegramService.SubscribeMessages:output_type -> pact.telegram.v1.MessageUpdate
	4, // [4:8] is the sub-list for method output_type
	0, // [0:4] is the sub-list for method input_type
	0, // [0:0] is the sub-list for extension type_name
	0, // [0:0] is the sub-list for extension extendee
	0, // [0:0] is the sub-list for field type_name
}

func init() { file_pact_telegram_v1_telegram_proto_init() }
func file_pact_telegram_v1_telegram_proto_init() {
	if File_pact_telegram_v1_telegram_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_pact_telegram_v1_telegram_proto_rawDesc), len(file_pact_telegram_v1_telegram_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   8,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_pact_telegram_v1_telegram_proto_goTypes,
		DependencyIndexes: file_pact_telegram_v1_telegram_proto_depIdxs,
		MessageInfos:      file_pact_telegram_v1_telegram_proto_msgTypes,
	}.Build()
	File_pact_telegram_v1_telegram_proto = out.File
	file_pact_telegram_v1_telegram_proto_goTypes = nil
	file_pact_telegram_v1_telegram_proto_depIdxs = nil
}
